version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      discovery.type: 'single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
    expose:
      - 9200
      - 9300
    networks:
      - elastic-network
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - '5000:5000'
  #   expose:
  #     - '5000'
  #   networks:
  #     - app-network
  #   depends_on: 
  #     - elasticsearch
  #   links:
  #     - elasticsearch
networks:
  elastic-network: